// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWjp0kMpHgQrlwSZ1J4cjgbujtTtSmfMQ',
    appId: '1:446238149840:web:a39f63a84aae3e75e3a2d5',
    messagingSenderId: '446238149840',
    projectId: 'vitallink-app',
    authDomain: 'vitallink-app.firebaseapp.com',
    storageBucket: 'vitallink-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuXgqNfE1D7963PRSmK_EPI7tukPWM4TM',
    appId: '1:446238149840:android:806d821f9554e9a9e3a2d5',
    messagingSenderId: '446238149840',
    projectId: 'vitallink-app',
    storageBucket: 'vitallink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdOkjQ2CWbyP1OPugSxnaTjBtohLpGFa4',
    appId: '1:446238149840:ios:dd0da4a89f9aa2d3e3a2d5',
    messagingSenderId: '446238149840',
    projectId: 'vitallink-app',
    storageBucket: 'vitallink-app.firebasestorage.app',
    iosBundleId: 'com.vitallink.vitallink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdOkjQ2CWbyP1OPugSxnaTjBtohLpGFa4',
    appId: '1:446238149840:ios:dd0da4a89f9aa2d3e3a2d5',
    messagingSenderId: '446238149840',
    projectId: 'vitallink-app',
    storageBucket: 'vitallink-app.firebasestorage.app',
    iosBundleId: 'com.vitallink.vitallink',
  );
}
