name: Flutter Quality Check

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Installer les dépendances
        run: flutter pub get

      - name: Vérifier le formatage du code (dart format)
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyser le code (flutter analyze)
        run: flutter analyze --no-fatal-infos
